language: go
go:
  - 1.6
  - 1.7

install:
  - mkdir $GOPATH/bin
  - curl https://glide.sh/get | sh
  - glide install
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls

script: ./scripts/test

after_success:
  - ./scripts/coveralls
