// This file was generated by counterfeiter
package projectfakes

import (
	"sync"

	go_tracker "github.com/odlp/go-tracker"
	"github.com/odlp/inflight/project"
)

type FakeProjectClient struct {
	ProjectMembershipsStub        func() ([]go_tracker.ProjectMembership, error)
	projectMembershipsMutex       sync.RWMutex
	projectMembershipsArgsForCall []struct{}
	projectMembershipsReturns     struct {
		result1 []go_tracker.ProjectMembership
		result2 error
	}
	StoriesStub        func(query go_tracker.StoriesQuery) ([]go_tracker.Story, go_tracker.Pagination, error)
	storiesMutex       sync.RWMutex
	storiesArgsForCall []struct {
		query go_tracker.StoriesQuery
	}
	storiesReturns struct {
		result1 []go_tracker.Story
		result2 go_tracker.Pagination
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProjectClient) ProjectMemberships() ([]go_tracker.ProjectMembership, error) {
	fake.projectMembershipsMutex.Lock()
	fake.projectMembershipsArgsForCall = append(fake.projectMembershipsArgsForCall, struct{}{})
	fake.recordInvocation("ProjectMemberships", []interface{}{})
	fake.projectMembershipsMutex.Unlock()
	if fake.ProjectMembershipsStub != nil {
		return fake.ProjectMembershipsStub()
	} else {
		return fake.projectMembershipsReturns.result1, fake.projectMembershipsReturns.result2
	}
}

func (fake *FakeProjectClient) ProjectMembershipsCallCount() int {
	fake.projectMembershipsMutex.RLock()
	defer fake.projectMembershipsMutex.RUnlock()
	return len(fake.projectMembershipsArgsForCall)
}

func (fake *FakeProjectClient) ProjectMembershipsReturns(result1 []go_tracker.ProjectMembership, result2 error) {
	fake.ProjectMembershipsStub = nil
	fake.projectMembershipsReturns = struct {
		result1 []go_tracker.ProjectMembership
		result2 error
	}{result1, result2}
}

func (fake *FakeProjectClient) Stories(query go_tracker.StoriesQuery) ([]go_tracker.Story, go_tracker.Pagination, error) {
	fake.storiesMutex.Lock()
	fake.storiesArgsForCall = append(fake.storiesArgsForCall, struct {
		query go_tracker.StoriesQuery
	}{query})
	fake.recordInvocation("Stories", []interface{}{query})
	fake.storiesMutex.Unlock()
	if fake.StoriesStub != nil {
		return fake.StoriesStub(query)
	} else {
		return fake.storiesReturns.result1, fake.storiesReturns.result2, fake.storiesReturns.result3
	}
}

func (fake *FakeProjectClient) StoriesCallCount() int {
	fake.storiesMutex.RLock()
	defer fake.storiesMutex.RUnlock()
	return len(fake.storiesArgsForCall)
}

func (fake *FakeProjectClient) StoriesArgsForCall(i int) go_tracker.StoriesQuery {
	fake.storiesMutex.RLock()
	defer fake.storiesMutex.RUnlock()
	return fake.storiesArgsForCall[i].query
}

func (fake *FakeProjectClient) StoriesReturns(result1 []go_tracker.Story, result2 go_tracker.Pagination, result3 error) {
	fake.StoriesStub = nil
	fake.storiesReturns = struct {
		result1 []go_tracker.Story
		result2 go_tracker.Pagination
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProjectClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.projectMembershipsMutex.RLock()
	defer fake.projectMembershipsMutex.RUnlock()
	fake.storiesMutex.RLock()
	defer fake.storiesMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeProjectClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ project.ProjectClient = new(FakeProjectClient)
