#!/bin/bash

set -e

SANDBOX=$(mktemp -d)

printf "Building Linux...\n"
GOOS=linux go build -o $SANDBOX/inflight-linux github.com/odlp/inflight

printf "Building OSX...\n"
GOOS=darwin go build -o $SANDBOX/inflight-osx github.com/odlp/inflight

printf "Building Windows...\n"
GOOS=windows go build -o $SANDBOX/inflight.exe github.com/odlp/inflight

printf "\nBuild summary:\n"
find $SANDBOX -type f -exec file {} \;

printf "\nSHA-1 digests for CF cli plugin repo:\n"
shasum $SANDBOX/inflight*

printf "\nBinaries are located here:\n$SANDBOX\n"
open $SANDBOX
